services:
  map_rando_videos:
    container_name: map_rando_videos
    image: map-rando-videos
    build:
      context: .
    ports:
      - '8081:8081'
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  db:
    image: postgres:16.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data 
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq:3.13.6
    container_name: rabbit
    restart: always
    hostname: "rabbit1"
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    ports:
      - '5672:5672'
volumes:
  dbdata:
  rabbitdata: